// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEmtDFbH72pfCIhf3tQvdPxyYlS0dXf64',
    appId: '1:263277157082:web:dbc679520e6345d51de3e3',
    messagingSenderId: '263277157082',
    projectId: 'bovineclassifer',
    authDomain: 'bovineclassifer.firebaseapp.com',
    storageBucket: 'bovineclassifer.firebasestorage.app',
    measurementId: 'G-QE4LVN7SKM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqG4mmBG4ayZfqwpTTaoRaJpflB-ksY2U',
    appId: '1:263277157082:android:5273c842ab9ec83b1de3e3',
    messagingSenderId: '263277157082',
    projectId: 'bovineclassifer',
    storageBucket: 'bovineclassifer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmjnMuK-NVxFa_jSoOGVciQbkx75mRlRc',
    appId: '1:263277157082:ios:038b35d1e1829f7b1de3e3',
    messagingSenderId: '263277157082',
    projectId: 'bovineclassifer',
    storageBucket: 'bovineclassifer.firebasestorage.app',
    iosBundleId: 'com.example.bovineClassifierApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmjnMuK-NVxFa_jSoOGVciQbkx75mRlRc',
    appId: '1:263277157082:ios:038b35d1e1829f7b1de3e3',
    messagingSenderId: '263277157082',
    projectId: 'bovineclassifer',
    storageBucket: 'bovineclassifer.firebasestorage.app',
    iosBundleId: 'com.example.bovineClassifierApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEmtDFbH72pfCIhf3tQvdPxyYlS0dXf64',
    appId: '1:263277157082:web:36a03d40d813e5021de3e3',
    messagingSenderId: '263277157082',
    projectId: 'bovineclassifer',
    authDomain: 'bovineclassifer.firebaseapp.com',
    storageBucket: 'bovineclassifer.firebasestorage.app',
    measurementId: 'G-X6NQGR4TDG',
  );
}
